export const hftRewards = {
    total: 1458.32,
    today: 7.22,
    weekly: 52.14,
    monthly: 215.67,
    history: [
      { date: "Jan", amount: 120 },
      { date: "Feb", amount: 145 },
      { date: "Mar", amount: 132 },
      { date: "Apr", amount: 167 },
      { date: "May", amount: 159 },
      { date: "Jun", amount: 178 },
      { date: "Jul", amount: 196 },
      { date: "Aug", amount: 214 },
      { date: "Sep", amount: 231 },
      { date: "Oct", amount: 247 },
    ],
    dailyAverage: [
      { day: "Mon", amount: 6.8 },
      { day: "Tue", amount: 7.2 },
      { day: "Wed", amount: 7.5 },
      { day: "Thu", amount: 6.9 },
      { day: "Fri", amount: 7.3 },
      { day: "Sat", amount: 7.8 },
      { day: "Sun", amount: 7.1 },
    ],
  }

export const usdRewards = {
    total: 4032.87,
    today: 19.85,
    weekly: 143.92,
    monthly: 594.76,
    history: [
      { date: "Jan", amount: 320 },
      { date: "Feb", amount: 385 },
      { date: "Mar", amount: 362 },
      { date: "Apr", amount: 427 },
      { date: "May", amount: 419 },
      { date: "Jun", amount: 458 },
      { date: "Jul", amount: 496 },
      { date: "Aug", amount: 534 },
      { date: "Sep", amount: 561 },
      { date: "Oct", amount: 587 },
    ],
    dailyAverage: [
      { day: "Mon", amount: 18.5 },
      { day: "Tue", amount: 19.2 },
      { day: "Wed", amount: 20.5 },
      { day: "Thu", amount: 18.9 },
      { day: "Fri", amount: 19.3 },
      { day: "Sat", amount: 21.8 },
      { day: "Sun", amount: 19.1 },
    ],
  }

export const leaderboard = [
    {
      rank: 1,
      username: "crypto_whale",
      avatar: "/placeholder.svg?height=32&width=32",
      rewards: 5842.67,
      change: "+12%",
    },
    { rank: 2, username: "trader_pro", avatar: "/placeholder.svg?height=32&width=32", rewards: 4721.39, change: "+8%" },
    {
      rank: 3,
      username: "blockmaster",
      avatar: "/placeholder.svg?height=32&width=32",
      rewards: 3968.14,
      change: "+5%",
    },
    {
      rank: 4,
      username: "satoshi_fan",
      avatar: "/placeholder.svg?height=32&width=32",
      rewards: 3542.91,
      change: "+3%",
    },
    { rank: 5, username: "hodl_king", avatar: "/placeholder.svg?height=32&width=32", rewards: 3127.45, change: "-2%" },
    {
      rank: 6,
      username: "crypto_guru",
      avatar: "/placeholder.svg?height=32&width=32",
      rewards: 2845.78,
      change: "+1%",
    },
    {
      rank: 7,
      username: "defi_master",
      avatar: "/placeholder.svg?height=32&width=32",
      rewards: 2634.19,
      change: "+4%",
    },
    { rank: 8, username: "you", avatar: "/placeholder.svg?height=32&width=32", rewards: 2458.32, change: "+7%" },
    { rank: 9, username: "eth_lover", avatar: "/placeholder.svg?height=32&width=32", rewards: 2312.67, change: "-1%" },
    {
      rank: 10,
      username: "btc_maximalist",
      avatar: "/placeholder.svg?height=32&width=32",
      rewards: 2187.93,
      change: "+2%",
    },
  ]
